{{- if eq .Values.scope "global" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: user-events-to-analytics
spec:
  replicas: 1
  connectCluster: analytics
  clusters:
    - alias: source
      bootstrapServers: {{ .Values.sourceBootstrap }}
    - alias: analytics
      bootstrapServers: {{ .Values.analyticsBootstrap }}
  mirrors:
    - sourceCluster: source
      targetCluster: analytics
      sourceConnector:
        config:
          topics: user-events
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 3
{{- end }}
